image:
  - Visual Studio 2019

install:
  - set _TROJAN_QT5_BUILD_INFO_=Trojan-Qt5 build from AppVeyor
  - set QTDIR=C:\Qt\5.14.2\msvc2017\bin
  - set PYDIR=C:\Python36
  - set GODIR=C:\go114-x86\bin
  - set GOROOT=C:\go114-x86
  - set MINGWDIR=C:\MinGW\bin
  - git clone https://github.com/Trojan-Qt5/Trojan-Qt5-Libraries.git C:\TQLibraries
  - cd C:\TQLibraries
  - 7z x Grpc.7z
  - cd C:\projects\trojan-qt5
  - curl -LO https://slproweb.com/download/Win32OpenSSL-1_1_1g.exe
  - powershell ".\\Win32OpenSSL-1_1_1g.exe /silent /sp- /suppressmsgboxes /DIR='C:\\TQLibraries\\OpenSSL-Win32'"
  - set PATH=%QTDIR%;%GODIR%;%PYDIR%;%MINGWDIR%;%PATH%;
  - git submodule update --init --recursive
  - cd 3rd\yaml-cpp && cmake -G "Visual Studio 16 2019" -A Win32 .
  - msbuild YAML_CPP.sln /p:Configuration=Release /p:Platform="Win32"
  - cd ..\..
  - cd 3rd\trojan-qt5-core
  - set GOARCH=386
  - go build --tags "api client router" -buildmode=c-shared -o trojan-qt5-core.dll main.go
  - process.bat
  - python msvc.py
  - cd ../..

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build\vcvarsall.bat x86

build_script:
  - mkdir build && cd build
  - qmake CONFIG+=release ..
  - nmake
  - cd release
  - windeployqt trojan-qt5.exe
  - del *.o *.h *.cpp *.stash *.qrc *.obj Makefile
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/move.py
  - python move.py
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/libiconv-2.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/libzbar-0.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/libssl-1_1.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/libcrypto-1_1.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/WinSparkle.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/cares.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/libprotobuf.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/libgcc_s_dw2-1.dll
  - curl -LO https://github.com/Trojan-Qt5/Trojan-Qt5-DLL/raw/master/zlib1.dll
  - del /f /s /q vc_redist.x86.exe opengl32sw.dll d3dcompiler_47.dll libGLESV2.dll libEGL.dll Qt5Svg.dll imageformats\qgif.dll iconengines\qsvgicon.dll imageformats\qtga.dll imageformats\qtiff.dll imageformats\qwbmp.dll imageformats\qwebp.dll imageformats\qjpeg.dll imageformats\qsvg.dll iconengines bearer
  - rmdir iconengines bearer
  - 7z a Trojan-Qt5-Windows.zip *
  - python ..\..\scripts\checksum.py Trojan-Qt5-Windows.zip Trojan-Qt5-Windows.hash
  - cd ..
  - cd ..

artifacts:
- path: 'build\release\Trojan-Qt5-Windows.*'
  name: Trojan-Qt5

deploy:
  provider: GitHub
  description: "Trojan-Qt5 Release"
  auth_token:
    secure: irJpr7f61rftnluing6Rqm7Q5Lxmk48O48F5t9/3KjaoMsIUh2lUb8SmXQmhkHY9
  artifact: Trojan-Qt5
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
