language: go

go:
  - 1.14.x

matrix:
  include:
    - os: osx
      osx_image: xcode11
      env: 
        - BADGE=osx
        - _TROJAN_QT5_BUILD_INFO_="Trojan-Qt5 build from Travis-CI"
    - os: linux
      dist: xenial
      sudo: required
      env: 
        - BADGE=linux
        - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH=${TRAVIS_BUILD_DIR}/recipes:${TRAVIS_BUILD_DIR}/bin:${PATH}
        - _TROJAN_QT5_BUILD_INFO_="Trojan-Qt5 build from Travis-CI"
      addons:
        apt:
          packages:
            - libxkbcommon-x11-0
            - libgl1-mesa-dev
      services:
        - xvfb

before_install:
  - if [ "$BADGE" = "linux" ]; then
      sudo add-apt-repository ppa:ymshenyu/grpc -y;
      sudo add-apt-repository ppa:savoury1/backports -y;
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update;
    fi
  - if [ "$BADGE" = "osx" ]; then
      brew update;
    fi

install:
  - if [ "$BADGE" = "linux" ]; then    
      sudo apt-get install gcc-7 g++-7 libqrencode-dev libzbar-dev libgl-dev git build-essential python-dev autoconf autotools-dev libicu-dev libbz2-dev checkinstall zlib1g zlib1g-dev python3 pkg-config libprotobuf-dev libgrpc++-dev protobuf-compiler protobuf-c-compiler protobuf-compiler-grpc libsodium-dev libuv1-dev -y;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7;
      git clone https://github.com/benlau/qtci.git;
      source qtci/path.env;
      install-qt 5.13.2 >/dev/null 2>&1;
      source qt-5.13.2.env;
      echo "Installing Zlib 1.2.11...";
      wget https://www.zlib.net/zlib-1.2.11.tar.gz >/dev/null 2>&1;
      tar -xf zlib-1.2.11.tar.gz;
      cd zlib-1.2.11;
      ./configure --prefix=/usr/local/zlib >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
      echo "Installing openssl 1.1.1g...";
      wget https://www.openssl.org/source/openssl-1.1.1g.tar.gz >/dev/null 2>&1;
      tar -xf openssl-1.1.1g.tar.gz;
      cd openssl-1.1.1g;
      ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl shared zlib >/dev/null 2>&1;
      make -j$(nproc) >/dev/null 2>&1;
      sudo make install >/dev/null 2>&1;
      cd ..;
    fi
  - if [ "$BADGE" = "osx" ]; then    
      brew install zbar qrencode openssl@1.1 zlib pcre python3 libsodium libuv grpc pkg-config;
      brew reinstall https://raw.githubusercontent.com/Homebrew/homebrew-core/8846805afc0cb8e5d114d5e222af1de3b35289df/Formula/qt.rb --verbose;
      rm -rf /usr/local/opt/protobuf/lib/libprotobuf-lite.*;
      cp -r framework/Sparkle.framework /usr/local/Cellar/qt/5.14.2/lib;
      cp -r framework/LetsMove.framework /usr/local/Cellar/qt/5.14.2/lib;
    fi

before_script:
  - if [ "$BADGE" = "osx" ];   then    export PATH="/usr/local/Cellar/qt/5.14.2/bin:$PATH"; fi

script:
  - git submodule update --init --recursive
  - cd 3rd/yaml-cpp
  - cmake . && make -j$(nproc)
  - cd ../..
  - cd 3rd/trojan-qt5-core
  - go build --tags "api client router" -buildmode=c-archive
  - cd ../..
  - if [ "$BADGE" = "osx" ]; then
      mkdir build && cd ./build;
      qmake ../;
      make -j$(nproc);
      xattr -c -r trojan-qt5.app;
      xattr -d com.apple.quarantine trojan-qt5.app;
      macdeployqt trojan-qt5.app -dmg;
      mv trojan-qt5.dmg Trojan-Qt5-macOS.dmg;
      brew link --overwrite python;
      python3 ../scripts/checksum.py Trojan-Qt5-macOS.dmg Trojan-Qt5-macOS.hash;
    fi
  - if [ "$BADGE" = "linux" ]; then
      mkdir build && cd ./build;
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
      qmake CONFIG+=release .. PREFIX=/usr;
      make -j$(nproc);
      make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/;
      export LD_LIBRARY_PATH=/usr/loal/zlib/lib:/usr/local/pcre/lib:/usr/local/zbar/lib/:/usr/local/qrencode/lib/:/usr/local/boost/lib/:/usr/local/openssl/lib/:$LD_LIBRARY_PATH;
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage;
      mv Trojan-Qt5*.AppImage Trojan-Qt5-Linux.AppImage;
      python3 ../scripts/checksum.py Trojan-Qt5-Linux.AppImage Trojan-Qt5-Linux.hash;
    fi

defore_deploy:
  - cd ..

deploy:
  provider: release
  file: 
    - build/Trojan-Qt5-macOS.dmg
    - build/Trojan-Qt5-macOS.hash
    - build/Trojan-Qt5-Linux.AppImage
    - build/Trojan-Qt5-Linux.hash
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true
